build-windows:
  tags:
    - saas-windows-medium-amd64
  before_script:
    - choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
    - choco install ninja -y
    - Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
    - Update-SessionEnvironment
    - choco install vulkan-sdk -y
    - Import-Module "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
    - Update-SessionEnvironment
    - C:\Python313\python.exe -m pip install numpy scipy colour-science
    - git clone https://github.com/andreavolpato/spektrafilm spektrafilm-parent
    - New-Item -ItemType Directory -Force -Path spektrafilm-parent\OFX\SpektraFilm
    - Get-ChildItem -Exclude spektrafilm-parent | Copy-Item -Destination spektrafilm-parent\OFX\SpektraFilm -Recurse -Force
  script:
    - cd spektrafilm-parent\OFX\SpektraFilm
    - cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
    - cmake --build build --config Release --parallel
  artifacts:
    name: spektrafilm-windows-ofx
    paths:
      - spektrafilm-parent/OFX/SpektraFilm/build/Release/**/*.ofx.bundle
      - spektrafilm-parent/OFX/SpektraFilm/build/**/*.zip
    expire_in: 2 weeks
